In [ ]:
# pandas learning with algonex

In [1]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Lenovo\AppData\Roaming\Python\Python314\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Lenovo\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Lenovo\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Lenovo\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\Lenovo\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
# series
a= pd.Series([1,2,3,34,56,678,9.8])
print(a)

0      1.0
1      2.0
2      3.0
3     34.0
4     56.0
5    678.0
6      9.8
dtype: float64

In [10]:
# dataframe
data={
    "locality": [ "whitefield","btm","indiranagar"],
    "rent":[50000,30000,60000],
    "size":[1000,1200,1500]
}
df=pd.DataFrame(data)
print(df)

      locality   rent  size
0   whitefield  50000  1000
1          btm  30000  1200
2  indiranagar  60000  1500

In [24]:
pd.__version__

'2.2.2'

In [8]:
pd.__version__

'3.0.2'

In [12]:
import pandas as pd 
D= pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")
print(D)

     Person ID  Gender  Age            Occupation  Sleep Duration  \
0            1    Male   27     Software Engineer             6.1
1            2    Male   28                Doctor             6.2
2            3    Male   28                Doctor             6.2
3            4    Male   28  Sales Representative             5.9
4            5    Male   28  Sales Representative             5.9
..         ...     ...  ...                   ...             ...
369        370  Female   59                 Nurse             8.1
370        371  Female   59                 Nurse             8.0
371        372  Female   59                 Nurse             8.1
372        373  Female   59                 Nurse             8.1
373        374  Female   59                 Nurse             8.1

     Quality of Sleep  Physical Activity Level  Stress Level BMI Category  \
0                   6                       42             6   Overweight
1                   6                       60             8       Normal
2                   6                       60             8       Normal
3                   4                       30             8        Obese
4                   4                       30             8        Obese
..                ...                      ...           ...          ...
369                 9                       75             3   Overweight
370                 9                       75             3   Overweight
371                 9                       75             3   Overweight
372                 9                       75             3   Overweight
373                 9                       75             3   Overweight

    Blood Pressure  Heart Rate  Daily Steps Sleep Disorder
0           126/83          77         4200            NaN
1           125/80          75        10000            NaN
2           125/80          75        10000            NaN
3           140/90          85         3000    Sleep Apnea
4           140/90          85         3000    Sleep Apnea
..             ...         ...          ...            ...
369         140/95          68         7000    Sleep Apnea
370         140/95          68         7000    Sleep Apnea
371         140/95          68         7000    Sleep Apnea
372         140/95          68         7000    Sleep Apnea
373         140/95          68         7000    Sleep Apnea

[374 rows x 13 columns]

In [15]:
D.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [16]:
D.tail()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [19]:
D.shape

(374, 13)

In [20]:
D.columns

Index(['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Quality of Sleep', 'Physical Activity Level', 'Stress Level',
       'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps',
       'Sleep Disorder'],
      dtype='str')

In [21]:
D.info()

<class 'pandas.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    str
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    str
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    str
 9   Blood Pressure           374 non-null    str
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    str
dtypes: float64(1), int64(7), str(5)
memory usage: 38.1 KB

In [24]:
D.size

4862

In [25]:
D.describe()

,Person ID,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.132086,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,0.795657,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,5.800000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.400000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.200000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,7.800000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,8.500000,9.000000,90.000000,8.000000,86.000000,10000.000000

In [34]:
 
import pandas as pd
# Properties
properties = pd.DataFrame({
    "property_id": [1,2,3],
    "owner_id": [101,102,103],
    "rent": [20000,50000,40000]
})

# Owners
owners = pd.DataFrame({
    "owner_id": [101,102],
    "owner_name": ["Ravi","Sita"]
})
# merge properties with owners on owner_id
merged_data=pd.merge(properties, owners, on="owner_id", how="left")
print(merged_data)

   property_id  owner_id   rent owner_name
0            1       101  20000       Ravi
1            2       102  50000       Sita
2            3       103  40000        NaN

In [1]:
import pandas as pd

In [3]:
transactions=pd.DataFrame({
    "date":["2023-01-01","2023-01-02","2023-01-03"],
    "store_nbr":[1,2,3],
    "lylty_card_nbr":[1001,1002,2003],
    "prod_name":['a','b','c'],
    "prod_qty":[10,20,30],
    'tot_sales':[100,200,300]


})
print(transactions)

         date  store_nbr  lylty_card_nbr prod_name  prod_qty  tot_sales
0  2023-01-01          1            1001         a        10        100
1  2023-01-02          2            1002         b        20        200
2  2023-01-03          3            2003         c        30        300

In [4]:
customers=pd.DataFrame({
    "lylty_card_nbr":[123,456,789],
    "lifestage":['young','middle_aged','old'],
    "premium_customer":['yes', 'no', 'yes']
})
print(customers)

   lylty_card_nbr    lifestage premium_customer
0             123        young              yes
1             456  middle_aged               no
2             789          old              yes

In [7]:
pd.merge(transactions, customers, on="lylty_card_nbr", how="left")

,date,store_nbr,lylty_card_nbr,prod_name,prod_qty,tot_sales,lifestage,premium_customer
0,2023-01-01,1,1001,a,10,100,NaN,NaN
1,2023-01-02,2,1002,b,20,200,NaN,NaN
2,2023-01-03,3,2003,c,30,300,NaN,NaN

In [8]:
pd.merge(transactions, customers, on="lylty_card_nbr", how="right")

,date,store_nbr,lylty_card_nbr,prod_name,prod_qty,tot_sales,lifestage,premium_customer
0,NaN,NaN,123,NaN,NaN,NaN,young,yes
1,NaN,NaN,456,NaN,NaN,NaN,middle_aged,no
2,NaN,NaN,789,NaN,NaN,NaN,old,yes

In [9]:
pd.__version__

'3.0.2'

In [12]:
print(transactions)

         date  store_nbr  lylty_card_nbr prod_name  prod_qty  tot_sales
0  2023-01-01          1            1001         a        10        100
1  2023-01-02          2            1002         b        20        200
2  2023-01-03          3            2003         c        30        300

In [18]:
transactions.groupby('store_nbr')['tot_sales'].sum()

store_nbr
1    100
2    200
3    300
Name: tot_sales, dtype: int64

In [19]:
transactions.groupby('prod_name')['tot_sales'].sum().sort_values(ascending=False).head(10)

prod_name
c    300
b    200
a    100
Name: tot_sales, dtype: int64

In [20]:
transactions.groupby('prod_name')['tot_sales'].sum().sort_values(ascending=False)

prod_name
c    300
b    200
a    100
Name: tot_sales, dtype: int64

In [21]:
transactions.groupby('lylty_card_nbr')['tot_sales'].sum().sort_values(ascending=False)

lylty_card_nbr
2003    300
1002    200
1001    100
Name: tot_sales, dtype: int64

In [27]:
transactions['date']= pd.to_datetime(transactions['date'])
transactions['month']= transactions['date'].dt.month
transactions.groupby('month')['tot_sales'].sum()
print(transactions)

        date  store_nbr  lylty_card_nbr prod_name  prod_qty  tot_sales  month
0 2023-01-01          1            1001         a        10        100      1
1 2023-01-02          2            1002         b        20        200      1
2 2023-01-03          3            2003         c        30        300      1

In [29]:
merged=pd.merge(transactions,customers, on="lylty_card_nbr", how="left")
print(merged)

        date  store_nbr  lylty_card_nbr prod_name  prod_qty  tot_sales  month  \
0 2023-01-01          1            1001         a        10        100      1
1 2023-01-02          2            1002         b        20        200      1
2 2023-01-03          3            2003         c        30        300      1

  lifestage premium_customer
0       NaN              NaN
1       NaN              NaN
2       NaN              NaN

In [ ]:
merged.groupby('lifestage')['tot_sales'].sum().sort_values(ascending=False)

Series([], Name: tot_sales, dtype: int64)

In [7]:
df1=pd.read_csv('Bellandur.csv')
df2=pd.read_csv('varthur.csv')
df3=pd.read_csv('Bommanahalli.csv')
df4=pd.read_csv('Whitefield.csv')
df5=pd.read_csv('yelahanka.csv')
df6=pd.read_csv('Electronic_city.csv')
df7=pd.read_csv('Mahadevapura.csv')
df8=pd.read_csv('Kaggadasapura.csv')
df9=pd.read_csv('Krishnarajapura.csv')
df10=pd.read_csv('Brookefield (1).csv')
df11=pd.read_csv('kr_puram.csv')
df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11], ignore_index=True)
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'Brookefield (1).csv'

In [ ]:
import pandas as pd

df1=pd.read_csv('Bellandur.csv')
df2=pd.read_csv('Varthur.csv')
df3=pd.read_csv('Bommanahalli.csv')
df4=pd.read_csv('Whitefield.csv')
df5=pd.read_csv('Yelahanka.csv')
df6=pd.read_csv('Electronic_City.csv')
df7=pd.read_csv('Mahadevapura.csv')
df8=pd.read_csv('Kaggadasapura.csv')
df9=pd.read_csv('Krishnarajapura.csv')
df10=pd.read_csv('Brookefield.csv')
df11=pd.read_csv('K.R Puram.csv')

df=pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11], ignore_index=True)
print(df)

                           property_id  type   activation_date  bathroom  \
0     ff808081482565740148261980670079  BHK3  11-02-2017 10:14         3
1     ff80808149b8764a0149bda1f264039d  BHK2  20-02-2017 17:36         2
2     ff8081814cb771fb014cc73874d531f6  BHK2  10-03-2017 19:12         2
3     ff8081814cb771fb014ccb09506b3b35  BHK1  06-03-2017 18:55         1
4     ff8081814cf0d662014cfedc2fcf38e6  BHK2  05-03-2017 14:30         2
...                                ...   ...               ...       ...
3327  ff8081815b055de1015b05a7591d121d  BHK2  25-03-2017 20:29         2
3328  ff8081815b056226015b056b652505ba  BHK2  25-03-2017 17:59         2
3329  ff8081815b05c342015b05f583d718d3  BHK1  25-03-2017 20:29         1
3330  ff8081815b199e90015b1b80e7936217  BHK2  30-03-2017 14:26         2
3331  ff8081815b1ebf9e015b1f04dca81b6f  BHK2  30-03-2017 17:26         2

      floor  total_floor      furnishing  gym   latitude  longitude  ...  \
0         1          1.0  SEMI_FURNISHED    1  12.947240  77.675158  ...
1         3          3.0  SEMI_FURNISHED    1  12.927401  77.663619  ...
2         4          NaN  SEMI_FURNISHED    1  12.925857  77.669326  ...
3         2          4.0  SEMI_FURNISHED    0  12.920241  77.668681  ...
4         4          5.0  SEMI_FURNISHED    0  12.924415  77.671483  ...
...     ...          ...             ...  ...        ...        ...  ...
3327      0          2.0  SEMI_FURNISHED    0  13.017465  77.706734  ...
3328      3          4.0  SEMI_FURNISHED    0  13.008378  77.696142  ...
3329      2          2.0  SEMI_FURNISHED    0  13.017573  77.706635  ...
3330      2          5.0  SEMI_FURNISHED    1  13.004017  77.687776  ...
3331      0          2.0  SEMI_FURNISHED    0  12.874122  77.594047  ...

       locality      parking property_age property_size  swimming_pool  \
0     Bellandur         BOTH            3          1617              1
1     Bellandur         BOTH            6          1450              1
2     Bellandur         BOTH            6          1100              0
3     Bellandur  TWO_WHEELER            1           450              0
4     Bellandur         BOTH            6          1150              0
...         ...          ...          ...           ...            ...
3327  K.R Puram  TWO_WHEELER           10          1000              0
3328  K.R Puram  TWO_WHEELER            2          1024              0
3329  K.R Puram  TWO_WHEELER           10           600              0
3330  K.R Puram         BOTH            0          1170              1
3331  K.R Puram  TWO_WHEELER            4          1200              0

      pin_code   rent  deposit  building_type  location
0     560037.0  33000   150000             AP       NaN
1     560102.0  25000   250000             AP       NaN
2          NaN  20000   100000            NaN       NaN
3     560102.0  14000    72000             AP       NaN
4     560103.0  20000   100000             AP       NaN
...        ...    ...      ...            ...       ...
3327  560049.0  12000   100000             IF       NaN
3328  560036.0  17000   170000             AP       NaN
3329  560049.0   8000    80000             IF       NaN
3330  560049.0  15000   100000             AP       NaN
3331  560076.0  14000   140000             IF       NaN

[3332 rows x 22 columns]

In [20]:
df

,bathroom,floor,total_floor,gym,latitude,longitude,lift,property_age,property_size,swimming_pool,...,locality_Krishnarajapura,locality_Mahadevapura,locality_Varthur,locality_Whitefield,locality_Yelahanka,parking_FOUR_WHEELER,parking_NONE,parking_TWO_WHEELER,building_type_IF,building_type_IH
0,3,1,1.000000,1,12.947240,77.675158,1,3,1617,1,...,False,False,False,False,False,False,False,False,False,False
1,2,3,3.000000,1,12.927401,77.663619,1,6,1450,1,...,False,False,False,False,False,False,False,False,False,False
2,2,4,4.833834,1,12.925857,77.669326,1,6,1100,0,...,False,False,False,False,False,False,False,False,False,False
3,1,2,4.000000,0,12.920241,77.668681,0,1,450,0,...,False,False,False,False,False,False,False,True,False,False
4,2,4,5.000000,0,12.924415,77.671483,1,6,1150,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,2,0,2.000000,0,13.017465,77.706734,0,10,1000,0,...,False,False,False,False,False,False,False,True,True,False
3328,2,3,4.000000,0,13.008378,77.696142,1,2,1024,0,...,False,False,False,False,False,False,False,True,False,False
3329,1,2,2.000000,0,13.017573,77.706635,0,10,600,0,...,False,False,False,False,False,False,False,True,True,False
3330,2,2,5.000000,1,13.004017,77.687776,1,0,1170,1,...,False,False,False,False,False,False,False,False,False,False
3331,2,0,2.000000,0,12.874122,77.594047,0,4,1200,0,...,False,False,False,False,False,False,False,True,True,False

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3332 entries, 0 to 3331
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_id      3332 non-null   object
 1   type             3332 non-null   object
 2   activation_date  3332 non-null   object
 3   bathroom         3332 non-null   int64
 4   floor            3332 non-null   int64
 5   total_floor      3328 non-null   float64
 6   furnishing       3332 non-null   object
 7   gym              3332 non-null   int64
 8   latitude         3332 non-null   float64
 9   longitude        3332 non-null   float64
 10  lease_type       3332 non-null   object
 11  lift             3332 non-null   int64
 12  locality         3108 non-null   object
 13  parking          3332 non-null   object
 14  property_age     3332 non-null   int64
 15  property_size    3332 non-null   int64
 16  swimming_pool    3332 non-null   int64
 17  pin_code         3299 non-null   float64
 18  rent             3332 non-null   int64
 19  deposit          3332 non-null   int64
 20  building_type    3325 non-null   object
 21  location         224 non-null    object
dtypes: float64(4), int64(9), object(9)
memory usage: 572.8+ KB

In [4]:
df.shape

(3332, 22)

In [5]:
df['rent'].describe()

count     3332.000000
mean     16637.692377
std      10194.502141
min       1023.000000
25%       9000.000000
50%      15000.000000
75%      22000.000000
max      75000.000000
Name: rent, dtype: float64

In [6]:
df[['rent', 'property_id']].describe()

               rent
count   3332.000000
mean   16637.692377
std    10194.502141
min     1023.000000
25%     9000.000000
50%    15000.000000
75%    22000.000000
max    75000.000000

In [7]:
df.head(10)

,property_id,type,activation_date,bathroom,floor,total_floor,furnishing,gym,latitude,longitude,...,locality,parking,property_age,property_size,swimming_pool,pin_code,rent,deposit,building_type,location
0,ff808081482565740148261980670079,BHK3,11-02-2017 10:14,3,1,1.0,SEMI_FURNISHED,1,12.947240,77.675158,...,Bellandur,BOTH,3,1617,1,560037.0,33000,150000,AP,NaN
1,ff80808149b8764a0149bda1f264039d,BHK2,20-02-2017 17:36,2,3,3.0,SEMI_FURNISHED,1,12.927401,77.663619,...,Bellandur,BOTH,6,1450,1,560102.0,25000,250000,AP,NaN
2,ff8081814cb771fb014cc73874d531f6,BHK2,10-03-2017 19:12,2,4,NaN,SEMI_FURNISHED,1,12.925857,77.669326,...,Bellandur,BOTH,6,1100,0,NaN,20000,100000,NaN,NaN
3,ff8081814cb771fb014ccb09506b3b35,BHK1,06-03-2017 18:55,1,2,4.0,SEMI_FURNISHED,0,12.920241,77.668681,...,Bellandur,TWO_WHEELER,1,450,0,560102.0,14000,72000,AP,NaN
4,ff8081814cf0d662014cfedc2fcf38e6,BHK2,05-03-2017 14:30,2,4,5.0,SEMI_FURNISHED,0,12.924415,77.671483,...,Bellandur,BOTH,6,1150,0,560103.0,20000,100000,AP,NaN
5,ff8081814eacc4b7014ead09cd41007d,BHK3,25-02-2017 12:57,3,0,5.0,SEMI_FURNISHED,0,12.924568,77.666805,...,Bellandur,BOTH,0,1690,0,560103.0,28000,200000,AP,NaN
6,ff8081814f3a5d61014f3b6ffb7b082d,BHK3,23-03-2017 14:56,3,4,4.0,FULLY_FURNISHED,0,12.934184,77.686504,...,Bellandur,BOTH,2,2238,0,560103.0,35000,350000,AP,NaN
7,ff80818150406cdf015041d70d7f0f18,BHK2,22-03-2017 21:17,1,2,4.0,SEMI_FURNISHED,0,12.920102,77.669594,...,Bellandur,TWO_WHEELER,7,800,0,560103.0,15000,100000,IF,NaN
8,ff808181505cf31901505fd917e80bdd,BHK3,24-02-2017 17:48,3,1,4.0,SEMI_FURNISHED,0,12.923495,77.685107,...,Bellandur,FOUR_WHEELER,2,1700,0,560103.0,40000,300000,AP,NaN
9,ff808181506fff08015074a16e282350,BHK2,23-03-2017 17:22,2,2,3.0,NOT_FURNISHED,0,12.904077,77.702914,...,Bellandur,BOTH,1,1477,0,560103.0,30000,200000,AP,NaN

In [8]:
df.isnull().sum()

property_id           0
type                  0
activation_date       0
bathroom              0
floor                 0
total_floor           4
furnishing            0
gym                   0
latitude              0
longitude             0
lease_type            0
lift                  0
locality            224
parking               0
property_age          0
property_size         0
swimming_pool         0
pin_code             33
rent                  0
deposit               0
building_type         7
location           3108
dtype: int64

In [9]:
df.isnull()

,property_id,type,activation_date,bathroom,floor,total_floor,furnishing,gym,latitude,longitude,...,locality,parking,property_age,property_size,swimming_pool,pin_code,rent,deposit,building_type,location
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3328,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3329,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3330,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3331,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [10]:
df['rent'].isnull().head(20)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: rent, dtype: bool

In [11]:
df[df['rent']>10000]

,property_id,type,activation_date,bathroom,floor,total_floor,furnishing,gym,latitude,longitude,...,locality,parking,property_age,property_size,swimming_pool,pin_code,rent,deposit,building_type,location
0,ff808081482565740148261980670079,BHK3,11-02-2017 10:14,3,1,1.0,SEMI_FURNISHED,1,12.947240,77.675158,...,Bellandur,BOTH,3,1617,1,560037.0,33000,150000,AP,NaN
1,ff80808149b8764a0149bda1f264039d,BHK2,20-02-2017 17:36,2,3,3.0,SEMI_FURNISHED,1,12.927401,77.663619,...,Bellandur,BOTH,6,1450,1,560102.0,25000,250000,AP,NaN
2,ff8081814cb771fb014cc73874d531f6,BHK2,10-03-2017 19:12,2,4,NaN,SEMI_FURNISHED,1,12.925857,77.669326,...,Bellandur,BOTH,6,1100,0,NaN,20000,100000,NaN,NaN
3,ff8081814cb771fb014ccb09506b3b35,BHK1,06-03-2017 18:55,1,2,4.0,SEMI_FURNISHED,0,12.920241,77.668681,...,Bellandur,TWO_WHEELER,1,450,0,560102.0,14000,72000,AP,NaN
4,ff8081814cf0d662014cfedc2fcf38e6,BHK2,05-03-2017 14:30,2,4,5.0,SEMI_FURNISHED,0,12.924415,77.671483,...,Bellandur,BOTH,6,1150,0,560103.0,20000,100000,AP,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3326,ff8081815b00b011015b011fcf130e72,BHK2,28-03-2017 13:47,2,0,4.0,SEMI_FURNISHED,0,13.003925,77.719403,...,K.R Puram,BOTH,0,1200,0,560049.0,15000,150000,AP,NaN
3327,ff8081815b055de1015b05a7591d121d,BHK2,25-03-2017 20:29,2,0,2.0,SEMI_FURNISHED,0,13.017465,77.706734,...,K.R Puram,TWO_WHEELER,10,1000,0,560049.0,12000,100000,IF,NaN
3328,ff8081815b056226015b056b652505ba,BHK2,25-03-2017 17:59,2,3,4.0,SEMI_FURNISHED,0,13.008378,77.696142,...,K.R Puram,TWO_WHEELER,2,1024,0,560036.0,17000,170000,AP,NaN
3330,ff8081815b199e90015b1b80e7936217,BHK2,30-03-2017 14:26,2,2,5.0,SEMI_FURNISHED,1,13.004017,77.687776,...,K.R Puram,BOTH,0,1170,1,560049.0,15000,100000,AP,NaN
3331,ff8081815b1ebf9e015b1f04dca81b6f,BHK2,30-03-2017 17:26,2,0,2.0,SEMI_FURNISHED,0,12.874122,77.594047,...,K.R Puram,TWO_WHEELER,4,1200,0,560076.0,14000,140000,IF,NaN

In [12]:
df[(df['rent'] < 10000) & (df['property_size'] <= 1000)]

,property_id,type,activation_date,bathroom,floor,total_floor,furnishing,gym,latitude,longitude,...,locality,parking,property_age,property_size,swimming_pool,pin_code,rent,deposit,building_type,location
13,ff80818151e74be30151e7b72f8c06e0,RK1,24-03-2017 19:14,1,4,4.0,SEMI_FURNISHED,0,12.934247,77.705276,...,Bellandur,BOTH,1,600,0,560037.0,6500,20000,AP,NaN
32,ff80818155f3f9b90155f89a3ee77556,BHK1,11-02-2017 17:03,1,3,3.0,SEMI_FURNISHED,0,12.930258,77.684053,...,Bellandur,TWO_WHEELER,11,450,0,560103.0,9000,40000,IF,NaN
140,ff8081815a56ab5d015a59d60a19748e,RK1,03-03-2017 10:49,1,0,4.0,FULLY_FURNISHED,0,12.929546,77.672455,...,Bellandur,TWO_WHEELER,3,130,0,560103.0,7000,60000,IF,NaN
146,ff8081815a6188c3015a63e8365e1e16,BHK1,22-02-2017 11:09,1,2,2.0,NOT_FURNISHED,0,12.947148,77.680385,...,Bellandur,TWO_WHEELER,5,400,0,560037.0,8000,50000,IF,NaN
153,ff8081815a69bafb015a6b273aa66b80,BHK3,13-03-2017 18:00,2,4,4.0,SEMI_FURNISHED,1,12.925233,77.677899,...,Bellandur,BOTH,6,1000,0,560103.0,7730,42000,AP,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3320,ff8081815ad73a10015ad73e0a6a021e,BHK1,16-03-2017 18:53,1,0,1.0,NOT_FURNISHED,0,13.009982,77.701769,...,K.R Puram,TWO_WHEELER,15,450,0,560036.0,8000,1,IF,NaN
3321,ff8081815ad73a10015ad74d0c85089c,BHK2,19-03-2017 12:42,1,0,1.0,NOT_FURNISHED,0,13.010923,77.704983,...,K.R Puram,TWO_WHEELER,10,850,0,560036.0,8000,50000,IF,NaN
3322,ff8081815ad73a10015ad7652ed713b1,RK1,16-03-2017 20:26,1,0,1.0,NOT_FURNISHED,0,13.008638,77.698815,...,K.R Puram,TWO_WHEELER,6,200,0,560036.0,3500,35000,IF,NaN
3323,ff8081815ad86bd8015adb95cb062a74,BHK1,17-03-2017 15:07,1,1,2.0,SEMI_FURNISHED,0,13.022794,77.705612,...,K.R Puram,TWO_WHEELER,5,500,0,560049.0,7500,30000,IF,NaN
3329,ff8081815b05c342015b05f583d718d3,BHK1,25-03-2017 20:29,1,2,2.0,SEMI_FURNISHED,0,13.017573,77.706635,...,K.R Puram,TWO_WHEELER,10,600,0,560049.0,8000,80000,IF,NaN

In [13]:
df['rent_per_sqft']= df['rent']/df['property_size']

In [14]:
df['rent_per_sqft'].head(10)

0    20.408163
1    17.241379
2    18.181818
3    31.111111
4    17.391304
5    16.568047
6    15.638963
7    18.750000
8    23.529412
9    20.311442
Name: rent_per_sqft, dtype: float64

In [15]:
#c=df.dropna(inplace=True)
#print(c)

In [16]:
df.dtypes

property_id         object
type                object
activation_date     object
bathroom             int64
floor                int64
total_floor        float64
furnishing          object
gym                  int64
latitude           float64
longitude          float64
lease_type          object
lift                 int64
locality            object
parking             object
property_age         int64
property_size        int64
swimming_pool        int64
pin_code           float64
rent                 int64
deposit              int64
building_type       object
location            object
rent_per_sqft      float64
dtype: object

In [6]:
import numpy as np
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(df.mean(numeric_only=True), inplace=True)

In [8]:
df['BHK'] = df['type'].str.extract(r'(\d+)').astype(int)

In [21]:
drop_cols = ['property_id', 'activation_date']
cat_cols = [c for c in df.select_dtypes(include=['object']).columns if c not in drop_cols]
df = df.drop(columns=drop_cols)
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)
df

KeyError: "['property_id', 'activation_date'] not found in axis"

In [19]:
df

,bathroom,floor,total_floor,gym,latitude,longitude,lift,property_age,property_size,swimming_pool,...,locality_Krishnarajapura,locality_Mahadevapura,locality_Varthur,locality_Whitefield,locality_Yelahanka,parking_FOUR_WHEELER,parking_NONE,parking_TWO_WHEELER,building_type_IF,building_type_IH
0,3,1,1.000000,1,12.947240,77.675158,1,3,1617,1,...,False,False,False,False,False,False,False,False,False,False
1,2,3,3.000000,1,12.927401,77.663619,1,6,1450,1,...,False,False,False,False,False,False,False,False,False,False
2,2,4,4.833834,1,12.925857,77.669326,1,6,1100,0,...,False,False,False,False,False,False,False,False,False,False
3,1,2,4.000000,0,12.920241,77.668681,0,1,450,0,...,False,False,False,False,False,False,False,True,False,False
4,2,4,5.000000,0,12.924415,77.671483,1,6,1150,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3327,2,0,2.000000,0,13.017465,77.706734,0,10,1000,0,...,False,False,False,False,False,False,False,True,True,False
3328,2,3,4.000000,0,13.008378,77.696142,1,2,1024,0,...,False,False,False,False,False,False,False,True,False,False
3329,1,2,2.000000,0,13.017573,77.706635,0,10,600,0,...,False,False,False,False,False,False,False,True,True,False
3330,2,2,5.000000,1,13.004017,77.687776,1,0,1170,1,...,False,False,False,False,False,False,False,False,False,False
3331,2,0,2.000000,0,12.874122,77.594047,0,4,1200,0,...,False,False,False,False,False,False,False,True,True,False

In [78]:
# df['location'].drop_duplicates()
# df['location'].unique()
# df = df.drop('location', axis=1, inplace=True)

train the dataset

In [23]:
X = df[['property_size', 'bathroom', 'BHK']]
y = pd.to_numeric(df['rent'], errors='coerce')
remaining_non_numeric = X.select_dtypes(exclude=['number','bool']).columns.tolist()
print('remaining non-numeric columns:', remaining_non_numeric)
if len(remaining_non_numeric) > 0:
    X = X.drop(columns=remaining_non_numeric)
X = X.select_dtypes(include=['number','bool']).astype(float)
print('numeric X shape:', X.shape)
print('X dtypes:', X.dtypes.unique())
print('y dtype:', y.dtype)
print('y missing values:', y.isna().sum())

remaining non-numeric columns: []
numeric X shape: (3332, 3)
X dtypes: [dtype('float64')]
y dtype: int64
y missing values: 0

In [24]:
import numpy as np
# y=pd.to_numeric(y, errors='coerce')

In [25]:
X = X.values.astype(float)
y = np.array(y, dtype=float)
print('X array dtype:', X.dtype)
print('y array dtype:', y.dtype)
mask = np.isfinite(X).all(axis=1) & np.isfinite(y)
print('valid rows:', mask.sum(), 'of', len(mask))
X = X[mask]
y = y[mask]

X array dtype: float64
y array dtype: float64
valid rows: 3332 of 3332

In [12]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\pasal\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in c:\users\pasal\anaconda3\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\pasal\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\pasal\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\pasal\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)

In [13]:
import sklearn

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

## **train the model**

In [29]:
X_train

array([[1.336e+03, 2.000e+00, 2.000e+00],
       [1.500e+03, 3.000e+00, 3.000e+00],
       [4.500e+02, 1.000e+00, 1.000e+00],
       ...,
       [1.000e+03, 2.000e+00, 2.000e+00],
       [1.200e+03, 2.000e+00, 2.000e+00],
       [1.180e+03, 2.000e+00, 2.000e+00]])

In [30]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [18]:
from sklearn.metrics import r2_score

predictions = model.predict(X_test)
print(r2_score(y_test, predictions))

-3.789038310435976

In [19]:
import pickle

pickle.dump(model, open("model.pkl", "wb"))